apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Users\Mark\AppData\Local\Microsoft\WinGet\Packages\Kubernetes.kompose_Microsoft.Winget.Source_8wekyb3d8bbwe\kompose.exe convert -f docker-compose.kubernetes.yml
    kompose.service.type: LoadBalancer
    kompose.version: 1.30.0 (9d8dcb518)
  creationTimestamp: null
  labels:
    io.kompose.service: api-tcp
  name: api-tcp
  namespace: default
spec:
  ports:
    - name: '5000'
      port: 5000
      targetPort: 5000
  selector:
    io.kompose.service: api
  type: LoadBalancer
status:
  loadBalancer: {}
