name: Build
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build:
    env:
      CI: true
      PORT: 5000
      HOST: http://localhost
      MONGO_URI: mongodb://localhost:27017/
      MONGO_DB_NAME: restapi
      MORGAN_ENABLED: 1
      MONGODB_LOGGER_ENABLED: 1
      SALT_WORK_FACTOR: 10
      PRIVATE_KEY: ${{vars.PRIVATE_KEY}}
      PUBLIC_KEY: ${{vars.PUBLIC_KEY}}
      ACCESS_TOKEN_TTL: 15
      REFRESH_TOKEN_TTL: 1440
    strategy:
      matrix:
        # platform: [ubuntu-latest, windows-latest, macos-latest]
        # node-version: [16.x, 18.x, 20.x]
        # mongodb-version: ['4.2', '4.4', '5.0', '6.0', '6.2']
        platform: [ubuntu-latest]
        node-version: [18.x]
        mongodb-version: ['6.0']
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Git checkout
        uses: actions/checkout@v3

      - name: Use Node.js versions ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Get node version
        id: node
        run: |
          echo "::set-output name=version::$(node -v)"

      - name: Get node_modules cache
        uses: actions/cache@v3.0.2
        id: node_modules
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('**/package-lock.json') }}-${{ steps.node.outputs.version }}

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.10.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}

      - run: npm install
      - run: npm run lint
      - run: npm run build
      - run: npm test
